# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default
  demands:
    - Agent.Name -equals Muneer
variables:
  acrName: 'mycontainerregistry788'
  imageName: 'apache-server'
  tag: 'latest'
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'mycontainerregistry788'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile.yml'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'manifests'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

