apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  labels:
    app: apache-server
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache-server
        image: mycontainerregistry788.azurecr.io/apache-server:TAG  # Update with your ACR URL
        ports:
        - containerPort: 80
