apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
        - name: apache-server
          image: mycontainerregistry788.azurecr.io/mycontainerregistry788/apache-server:472012
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret  # Ensure you have a valid ACR authentication secret
