apiVersion: v1
kind: Service
metadata:
  name: apache-server-service
spec:
  selector:
    app: apache-server
  type: LoadBalancer  # Expose externally
  ports:
  - protocol: TCP
    port: 80  # Public Port
    targetPort: 80  # Container Port
